redux and react app init
actimeller/react-underhood-redux-lesson pull request #1
Opened 2020-08-14 17:12 UTC by actimeller

2020-08-17 18:40 UTC, oceandrama requested changes

2020-08-17 18:40 UTC, oceandrama commented on react-redux/src/items.json
> +      "type": "done",
`status` бы подошёл чуть лучше

2020-08-17 18:40 UTC, oceandrama commented on react-redux/src/Connect/Connect.jsx
> +        const unsubscribe = store.subscribe(this.listener);
Ты же подписался на 18 строке, зачем это делать ещё раз?
Так у тебя второй раз добавится подписчик и сразу же удалится, а первый так и останется

2020-08-17 18:40 UTC, oceandrama commented on react-redux/src/Connect/Connect.jsx
> +        this.setState(mapStateToProps(stateFromStore));
Немного странно, почему ты результат `mapStateToProps` сохраняешь в стейте, а `mapDispatchToProps` просто передаешь в дочерние компоненты. Результат `mapStateToProps` ты больше нигде не используешь
Если ты делаешь так, что вызвать ререндер при изменении стейта, то можно просто в обработчике подписки вызывать `forceRender`, например

2020-08-17 18:40 UTC, oceandrama commented on redux/redux.js
> +    function applyMiddleware(store, middlewares) {
Эту функцию можно объявить вне `createStore`

2020-08-17 18:40 UTC, oceandrama commented on redux/redux.js
> +    if (middlewares) applyMiddleware(store, middlewares);
Результат вызова `applyMiddleware` не нужно записать в `store`?

2020-08-17 18:40 UTC, oceandrama commented on redux/redux.js
> +      Object.entries(reducers).forEach((reducer) => {
Можно деструктурировать тут
```
forEach(([key, fn]) => {...
```

2020-08-17 18:40 UTC, oceandrama commented on redux/redux.js
> +    this.reducer = this.reducer.bind(this);
А можно одной строкой записать?
```
this.reducer = reducer.bind(this);
```

2020-08-17 18:40 UTC, oceandrama commented on redux/redux.js
> +    if (typeof action === 'function') return action(this.state)
Это ты хотел `redux-thunk` реализовать? В ядре `redux` этой строчке не место. Нужно реализовать через `middleware`

2020-08-17 18:40 UTC, oceandrama commented on redux/redux.js
> +    // здесь должна быть реализация
Тут тоже можно добавить реализацию

2020-08-17 18:40 UTC, oceandrama commented on react-redux/src/Todo/Todo.jsx
> +      <TodoContent items={props.items} />
У тебя и этот компонент пытается прокинуть список элементов, и сам `TodoContent` пытается подключиться к стору. Нужно оставить один вариант

2020-08-17 18:40 UTC, oceandrama commented on react-redux/src/Todo/TodoContent.jsx
> +          .filter((item) => item.type === "planned")
Эту фильтрацию лучше реализовать внутри `connect`. Чтобы не перерендеривать весь компонент в случае изменения только одного списка

2020-08-17 18:40 UTC, oceandrama commented on react-redux/src/Reducer/Reducer.js
> +export const deleteAction = (value) => ({
Можно заметить, что все функции для создания экшенов выглядят одинаково. Их самих тоже можно создавать с помощью фабрик. Т.е. сделать функцию, которая будет возвращать функцию для созадния экшена

2020-08-17 21:03 UTC, actimeller commented on react-redux/src/items.json
> +      "type": "done",
++

2020-08-17 21:08 UTC, actimeller commented on react-redux/src/Connect/Connect.jsx
> +        const unsubscribe = store.subscribe(this.listener);
исправил

2020-08-17 21:09 UTC, actimeller commented on react-redux/src/Connect/Connect.jsx
> +        this.setState(mapStateToProps(stateFromStore));
Мне кажется странным вызывать `forceRender` , почему setState не подходит для обновления состояния?

2020-08-17 21:17 UTC, actimeller commented on redux/redux.js
> +    function applyMiddleware(store, middlewares) {
++

2020-08-17 21:20 UTC, actimeller commented on redux/redux.js
> +    if (middlewares) applyMiddleware(store, middlewares);
нет

2020-08-17 21:24 UTC, actimeller commented on redux/redux.js
> +      Object.entries(reducers).forEach((reducer) => {
++

2020-08-17 21:24 UTC, actimeller commented on redux/redux.js
> +    this.reducer = this.reducer.bind(this);
++

2020-08-17 21:27 UTC, actimeller commented on redux/redux.js
> +    if (typeof action === 'function') return action(this.state)
Прошу дать более полное описание задачи. Я уже спрашивал, не получил ответа и реализовал таким образом. 
Как реализовать через мидлвар я не знаю.

2020-08-17 21:29 UTC, actimeller commented on redux/redux.js
> +    // здесь должна быть реализация
Я же спрашивал? Решили остановиться на удаление подписчика при повторной подписке

2020-08-17 21:29 UTC, actimeller commented on react-redux/src/Todo/Todo.jsx
> +      <TodoContent items={props.items} />
Пережиток прошлгого. Убрал

2020-08-17 21:44 UTC, actimeller commented on react-redux/src/Todo/TodoContent.jsx
> +          .filter((item) => item.type === "planned")
Не понимаю. Если пропсы изменятся, то компонент в любом случае отрендерится заново. Чтобы этого избежать - надо дробить делать какой-то общий компонент и передавать только нужный пропс со статусом. 
Но я намеренно не стал усложнять структуру, т.к. цель урока redux, а не лишние рендеры

2020-08-17 21:58 UTC, actimeller commented on react-redux/src/Reducer/Reducer.js
> +export const deleteAction = (value) => ({
++

2020-08-17 21:59 UTC, actimeller commented on redux/redux.js
> +    if (middlewares) applyMiddleware(store, middlewares);
При попытке записать, получаю ошибки с bind(this), поэтому оставил просто модификацию

2020-08-19 07:33 UTC, oceandrama commented on react-redux/src/Connect/Connect.jsx
> +        this.setState(mapStateToProps(stateFromStore));
Тебе нужно использовать здесь состояние? Ты же его просто прокидываешь дальше. Мы же писали реализацию `setState`. Он под капотом и так вызывает `forceRender`, почему тебе не нравится его использовать?

2020-08-19 07:34 UTC, oceandrama commented on redux/redux.js
> +    this.reducer = this.reducer.bind(this);
Эм, это странно. У тебя бывают ситуации, когда ты не передаешь `reducer`?

2020-08-19 07:39 UTC, oceandrama requested changes

2020-08-19 07:39 UTC, oceandrama commented on redux/redux.js
> +    // здесь должна быть реализация
Я не говорю, что нужно удалять ту реализацию. В разных ситуациях бывает удобнее использовать той или иной подход. Когда подписка и отписка происходит в одной функции - удобнее вызывать результат `subsrcibe`. Когда в разных - нужно где-то его сохранять, чтобы этого не делать можно просто вызвать `unsubscribe`

2020-08-19 07:39 UTC, oceandrama commented on redux/redux.js
> +    if (middlewares) applyMiddleware(store, middlewares);
Я не очень понимаю, в каком моменте ты модифицируешь стор? Ты же оттуда возвращаешь новый объект.
Не нужно обходить ошибки, мы здесь, чтобы разобраться с ними

2020-08-19 07:39 UTC, oceandrama commented on redux/redux.js
> +    if (typeof action === 'function') return action(this.state)
Ну, например, вот исходники самого `redux-thunk`
https://github.com/reduxjs/redux-thunk/blob/master/src/index.js

2020-08-19 07:40 UTC, oceandrama commented on react-redux/src/Connect/Connect.jsx
> +        store.subscribe(this.listener.bind(this));
Зачем ты подписываешь на анмаунте? Ты наоборот должен отписаться

2020-08-19 07:41 UTC, oceandrama commented on redux/redux.js
> +    if (middlewares) module.exports.applyMiddleware(store, middlewares);
А тебе нужно эспортировать `applyMiddleware`? Можно объявить его ещё выше

2020-08-19 07:48 UTC, oceandrama commented on react-redux/src/Todo/TodoContent.jsx
> +          .filter((item) => item.type === "planned")
Это не усложнение структуры, а стандартный подход в случае с редаксом. У тебя есть "глупый" компонент, который рендерит списки. Ты в него закладываешь знания о том, как именно их нужно фильтровать. У тебя появляется дублирование кода. Ты бы мог создать компонент, который рендерит один список, а не 3, и переиспользовать его, и вот тут уже оптимизации рендера сыграли бы свою роль

2020-08-19 19:03 UTC, actimeller commented on react-redux/src/Connect/Connect.jsx
> +        this.setState(mapStateToProps(stateFromStore));
Разве мы писали реализацию `forceRender` ?

2020-08-19 19:32 UTC, actimeller commented on react-redux/src/Connect/Connect.jsx
> +        this.setState(mapStateToProps(stateFromStore));
> Если ты делаешь так, что вызвать ререндер при изменении стейта, то можно просто в обработчике подписки вызывать forceRender, например

Что такое "обработчик подписки"? 
Часть redux.js  ```   subscribe(fn) { ``` ? Как из редакса вызывать forceUpdate компонента?

2020-08-19 19:36 UTC, actimeller commented on redux/redux.js
> +    if (middlewares) applyMiddleware(store, middlewares);
Функция работает и без return'a. Я модифицирую внутри forEach
Убрал return, чтобы не смущал

2020-08-19 19:41 UTC, actimeller commented on redux/redux.js
> +    this.reducer = this.reducer.bind(this);
Это результаты из теста redux.test.js . Все ситуации оттуда.

2020-08-19 19:43 UTC, actimeller commented on redux/redux.js
> +    this.reducer = this.reducer.bind(this);
исправил

2020-08-19 19:45 UTC, actimeller commented on redux/redux.js
> +    if (middlewares) module.exports.applyMiddleware(store, middlewares);
++

2020-08-19 20:10 UTC, actimeller commented on redux/redux.js
> +    if (typeof action === 'function') return action(this.state)
Где мне использовать это?

2020-08-19 20:19 UTC, actimeller commented on react-redux/src/Connect/Connect.jsx
> +        store.subscribe(this.listener.bind(this));
++

2020-08-19 20:19 UTC, actimeller commented on redux/redux.js
> +    // здесь должна быть реализация
++

2020-08-19 21:24 UTC, actimeller commented on react-redux/src/Connect/Connect.jsx
> +        this.setState(mapStateToProps(stateFromStore));
Переделал
++

2020-08-19 21:25 UTC, actimeller commented on react-redux/src/Todo/TodoContent.jsx
> +          .filter((item) => item.type === "planned")
++

2020-08-20 06:12 UTC, oceandrama commented on react-redux/src/Connect/Connect.jsx
> +        this.setState(mapStateToProps(stateFromStore));
`forceRender` - это низкоуровневый API, который действительно нечасто используется, но знать и уметь им пользоваться нужно
А что именно ты переделал?

2020-08-20 06:13 UTC, oceandrama commented on redux/redux.js
> +    if (typeof action === 'function') return action(this.state)
`redux-thunk` - это `middleware`, ты можешь подключать его по умолчанию при создании стора, например

2020-08-20 06:17 UTC, actimeller commented on redux/redux.js
> +    if (typeof action === 'function') return action(this.state)
Подключать в любом случае?

2020-08-20 06:34 UTC, oceandrama commented on react-redux/src/Todo/TodoColumn.jsx
> +  constructor(props) {
Конструктор можно опустить

2020-08-20 06:34 UTC, oceandrama commented on react-redux/src/Todo/TodoContent.jsx
> +    plannedItems: items.filter((item) => item.status === "planned"),
Ну красота же

2020-08-20 06:36 UTC, oceandrama commented on react-redux/src/Connect/Connect.jsx
>          store.subscribe(this.listener.bind(this));
А отписаться?

2020-08-20 06:40 UTC, oceandrama commented on react-redux/src/Todo/TodoControls.jsx
> +      const activeItem = items.filter((item) => item.id === activeItemId)[0];
Можно использовать `find`

2020-08-20 06:49 UTC, oceandrama commented on redux/redux.js
> +    if (typeof action === 'function') return action(this.state)
Ну, в текущем проекте, например, у тебя не было такой необходимости. В любом случае, это нужно делать явно.
В тесте редакса этот мидлвар подключается прям там. Так что я бы просто удалил эту строку. Если упадет тест на редакс - смотреть, что не так с обработкой самих мидлваров

2020-08-20 06:52 UTC, oceandrama commented on react-redux/src/Todo/TodoControls.jsx
> +    if (!activeItemId || activeItemId === null)
Если хочешь проверить на undefined и null, можно сравнить так `activeItemId == null`

2020-08-20 15:50 UTC, actimeller commented on react-redux/src/Connect/Connect.jsx
> +        this.setState(mapStateToProps(stateFromStore));
Не запушил, проверь еще раз пожалуйста

2020-08-20 15:51 UTC, actimeller commented on react-redux/src/Todo/TodoColumn.jsx
> +  constructor(props) {
++

2020-08-20 15:53 UTC, mvodyanov commented on react-redux/src/Todo/TodoControls.jsx
> +      const activeItem = items.filter((item) => item.id === activeItemId)[0];
++

2020-08-20 15:53 UTC, actimeller commented on react-redux/src/Todo/TodoControls.jsx
> +    if (!activeItemId || activeItemId === null)
++

2020-09-01 19:26 UTC, merged